--MEMBER 테이블 생성
DROP TABLE MEMBER;

CREATE TABLE MEMBER(
    USERNO NUMBER PRIMARY KEY,
    USERID VARCHAR2(15) NOT NULL UNIQUE,
    USERPWD VARCHAR2(20) NOT NULL,
    USERNAME VARCHAR2(20) NOT NULL,
    GENDER CHAR(1) CHECK (GENDER IN ('M','F')),
    AGE NUMBER,
    EMAIL VARCHAR2(30),
    PHONE CHAR(11),
    ADDRESS VARCHAR2(100),
    HOBBY VARCHAR2(50),
    ENROLLDATE DATE DEFAULT SYSDATE NOT NULL
);

--회원번호를 발생시킬 시퀀스 생성
DROP SEQUENCE SEQ_USERNO;

CREATE SEQUENCE SEQ_USERNO NOCACHE;
    
--MEMBER 테이블에 테스트데이터 삽입
INSERT INTO MEMBER
VALUES (SEQ_USERNO.NEXTVAL, 'admin', '1234', '관리자', 'M', 45, 'admin@naver.com', 01012345678, '서울시 영등포구', '숨쉬기', '2021/01/25');

INSERT INTO MEMBER
VALUES (SEQ_USERNO.NEXTVAL, 'user01', 'pass01', '홍길동', 'F', 23, NULL, 01056789123, NULL, '영화보기', '2021/07/21');

COMMIT;

SELECT * FROM MEMBER;